In [3]:
%matplotlib nbagg
#%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation
print("start!")

rnorm=np.ones(20)
print (rnorm)

ims = []
dataall=[]
print(dataall)
dataall=np.zeros((4000, 2409))
N = 2409  # 1レコード番号あたりに格納されているデータの数。
M = 4000  # レコードの総数。
numb=1
for i in range(8):
    fol=format(i, '03b')
    for j in range(10):
        numb+=1
        mass="{0:02d}".format(j+1)
        fname='./glbdsk_str'+fol+"M"+mass+'.dat'
        f = open(fname, 'r')
        dty = np.dtype([('data', '<' + str(N) + 'f')])
        chunk = np.fromfile(f, dtype=dty, count=M)
        data = []
        for k in range(M):
            data.append(chunk[k]['data'])
        data=np.array(data)
        dataall=np.dstack((dataall, data))
        if(j==7):
            print(fname,numb)

        #print(dataall.nbytes)
#print(dataall.shape)
print("end")

import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
import multiprocessing as mp
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.animation as animation
from matplotlib import gridspec
from astropy.modeling.models import BlackBody1D
from astropy.modeling.blackbody import FLAM
from astropy import units as u
from astropy.visualization import quantity_support
from astropy.modeling.blackbody import blackbody_lambda
print("end2")

box_size_xmin = 1e-01
box_size_xmax = 1e+04
box_size_ymin = 1e-06
box_size_ymin = 1e-20
box_size_ymax = 1e+02
pis=np.pi*2*1.04e-15*1e+4
wav = np.logspace(4,7,27) * u.AA
fluxtest = blackbody_lambda(wav[1], 1000*u.K)*wav[1]
#wavobs=(0.44e-23*3e14/(wav))* u.AA*fluxtest.unit
wavobs=(0.44e-23*3e22/(wav))* u.AA*fluxtest.unit# L=M^2
cmap=plt.get_cmap("tab10")
obs=np.array([1,2,3,5,6,10,12,16,17])
lifetime=np.ones((30, 10,8))

cmap=plt.get_cmap("tab10")
limK=5
limKhigh=150
limKmid=50
limKlow=10



start!
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[]
./glbdsk_str000M08.dat 9
./glbdsk_str001M08.dat 19
./glbdsk_str010M08.dat 29
./glbdsk_str011M08.dat 39
./glbdsk_str100M08.dat 49
./glbdsk_str101M08.dat 59
./glbdsk_str110M08.dat 69
./glbdsk_str111M08.dat 79
end
end2


In [6]:
obs=np.array([1,2,3,5,6,10,12,16,17])
lall=np.zeros((30,10,0))
print(lall)
for inital in range(8):
    lifetime1=np.loadtxt("test"+str(inital)+"0510.csv", delimiter=',')
    print(lifetime1.shape)
    lifetime1=lifetime1.reshape(30, 10,1)
    print(lifetime1.shape)
    lall=np.append(lall,lifetime1,axis=2)
    print(lall.shape)
lifetime=lall

[]
(30, 10)
(30, 10, 1)
(30, 10, 1)
(30, 10)
(30, 10, 1)
(30, 10, 2)
(30, 10)
(30, 10, 1)
(30, 10, 3)
(30, 10)
(30, 10, 1)
(30, 10, 4)
(30, 10)
(30, 10, 1)
(30, 10, 5)
(30, 10)
(30, 10, 1)
(30, 10, 6)
(30, 10)
(30, 10, 1)
(30, 10, 7)
(30, 10)
(30, 10, 1)
(30, 10, 8)


In [ ]:
wavobs=(0.44e-23*3e22/(wav))* u.AA*fluxtest.unit# L=M^2
lifetime=np.ones((30, 10,8))

import time
import datetime

start = time.time()

pltdat=dataall[:,:,1]
x =pltdat[:,0]
for inicon in range(6):
    inicon=inicon+2  #restart +? 8-?
    ini=(inicon+1)*10
    print(ini,"   ",datetime.datetime.now())
    for i in range(300):  #time to300 or short test
        for j in range(10): #10=0.1~1.0 1=1mass
            if i%100==0:
                t = time.time() - start
                print(ini,"   ",i,"   ",j,"   ",t,"   ",datetime.datetime.now())
            ininum=ini-9+j
            pltdat=dataall[:,:,ininum]
            s =pltdat[:,i+1]                          
            s[s<1e-8]=0 #kagen ika ha 0 ni suru   
            #s[s<1e-6]=0 #kagen ika ha 0 ni suru
            t =pltdat[:,i+301]             
            m=0
            l=0
            fluxall = 0
            while (t[l]>limKlow):
                l=m
                flux = blackbody_lambda(wav, t[l]*u.K)
                kei=(1-np.exp(-(10*s[l])))*x[l]*(x[l+1]-x[l])
                F=flux*kei*pis
                fluxall+=F
                m+=1
            if i>2:
                for k in obs:
                    if fluxall[k]*wav[k]>wavobs[k]:
                        lifetime[k,j,inicon]=i
print(lifetime)

30     2020-05-10 22:26:00.906370
30     0     0     0.0005869865417480469     2020-05-10 22:26:00.906543
30     0     1     0.003212451934814453     2020-05-10 22:26:00.909178
30     0     2     0.0057561397552490234     2020-05-10 22:26:00.911720
30     0     3     0.00755620002746582     2020-05-10 22:26:00.913514
30     0     4     0.00835728645324707     2020-05-10 22:26:00.914315
30     0     5     0.009285211563110352     2020-05-10 22:26:00.915243
30     0     6     0.010171175003051758     2020-05-10 22:26:00.916129
30     0     7     0.011068582534790039     2020-05-10 22:26:00.917026
30     0     8     0.01180720329284668     2020-05-10 22:26:00.917764
30     0     9     0.012571573257446289     2020-05-10 22:26:00.918529


/home/porco/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/site-packages/astropy/units/quantity.py:639: RuntimeWarning: overflow encountered in multiply
  result = super().__array_ufunc__(function, method, *arrays, **kwargs)
/home/porco/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/site-packages/astropy/units/quantity.py:639: RuntimeWarning: overflow encountered in expm1
  result = super().__array_ufunc__(function, method, *arrays, **kwargs)


30     100     0     6519.163604021072     2020-05-11 00:14:40.069564
30     100     1     6523.970261096954     2020-05-11 00:14:44.876221
30     100     2     6529.322713375092     2020-05-11 00:14:50.228674
30     100     3     6535.25998544693     2020-05-11 00:14:56.165945
30     100     4     6541.600711345673     2020-05-11 00:15:02.506671
30     100     5     6548.191658973694     2020-05-11 00:15:09.097619
30     100     6     6555.12327170372     2020-05-11 00:15:16.029232
30     100     7     6562.506205320358     2020-05-11 00:15:23.412165
30     100     8     6570.043667554855     2020-05-11 00:15:30.949627
30     100     9     6577.7178699970245     2020-05-11 00:15:38.623829
30     200     0     13161.445322275162     2020-05-11 02:05:22.351282
30     200     1     13166.213819026947     2020-05-11 02:05:27.119779
30     200     2     13171.495267152786     2020-05-11 02:05:32.401227
30     200     3     13177.293724775314     2020-05-11 02:05:38.199685
30     200     4 

In [ ]:
for inital in range(8):
    for obsw in obs:
        print(lifetime[obsw,:,inital])

In [ ]:
for inital in range(8):
    #print(lifetime[:,:,inital])
    np.savetxt("test"+str(inital)+"0510.csv", lifetime[:,:,inital], delimiter=',')

In [ ]:
for j in range(10):
    #print(lifetime[:,:,inital])
    np.savetxt("test0"+str(j)+"0510.csv", lifetime[:,j,:], delimiter=',')

In [ ]:
wav1 = np.logspace(4,7,27)
print(wav1/10000)

obsa=np.array([1.2,1.6,2.1,3.4,4.6,12,22,65,90])

for k in obsa:
                print(np.count_nonzero((wav1/10000)<k))
obs=[1,2,3,5,6,10,12,16,17]
for k in obs:
                print(wav1[k]/10000)

In [7]:
for inital in range(8):
    print(lifetime[:,:,inital])

[[  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1. 299.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1. 299.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1. 299.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1. 299.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1. 299.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1. 299.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1. 299.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1. 299.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1. 299.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.