In [35]:
%matplotlib nbagg
#%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation
print("end")
import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
import multiprocessing as mp
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.animation as animation
from matplotlib import gridspec
from astropy.modeling.models import BlackBody1D
from astropy.modeling.blackbody import FLAM
from astropy import units as u
from astropy.visualization import quantity_support
from astropy.modeling.blackbody import blackbody_lambda
print("end2")


cmap=plt.get_cmap("tab10")
obs=np.array([8,9,10,11,12,15,17,20,22])
lifetime=np.ones((30, 10,8))


for inicon in range(8):
    for j in range(10): #10=0.1~1.0 1=1mass
        for k in obs:
            lifetime[k,j,inicon]=inicon+j+k
            
print(lifetime)
for inital in range(8):
    print(lifetime[:,:,inital])

end
end2
[[[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 ...

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]]
[

In [39]:
lifetime=np.array([[[  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.],
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.],
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.],
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.],
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.],
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.],
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.],
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.],
 [299. 299. 299. 299. 299. 299. 299. 299. 299. 299.],
 [299. 299. 299. 299. 299. 299. 299. 299. 299. 299.],
 [299. 299. 299. 299. 299. 299. 299. 299. 299. 299.],
 [299. 299. 299. 299. 299. 299. 299. 299. 299. 299.],
 [299. 299. 299. 299. 299. 299. 299. 299. 299. 299.],
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.],
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.],
 [299. 299. 299. 299. 299. 299. 299. 299. 299. 299.],
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.],
 [299. 299. 299. 299. 299. 299. 299. 299. 299. 299.],
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.],
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.],
 [299. 299. 299. 299. 299. 299. 299. 299. 299. 299.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [299. 299. 299. 299. 299. 299. 299. 299. 299. 299.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]]
[[  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  7. 299. 299. 299. 299. 299. 299. 299. 299. 299.]
 [  8. 299. 299. 299. 299. 299. 299. 299. 299. 299.]
 [  8. 299. 299. 299. 299. 299. 299. 299. 299. 299.]
 [  8. 299. 299. 299. 299. 299. 299. 299. 299. 299.]
 [  8. 299. 299. 299. 299. 299. 299. 299. 299. 299.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  7. 299. 299. 299. 299. 299. 299. 299. 299. 299.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  7. 299. 299. 299. 299. 299. 299. 299. 299. 299.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  7. 299. 299. 299. 299. 299. 299. 299. 299. 299.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  7. 299. 299. 299. 299. 299. 299. 299. 299. 299.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]]
[[  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [207. 190. 186. 186. 299. 299. 299. 299. 299. 299.]
 [213. 191. 186. 299. 299. 299. 299. 299. 299. 299.]
 [214. 191. 187. 299. 299. 299. 299. 299. 299. 299.]
 [215. 191. 187. 299. 299. 299. 299. 299. 299. 299.]
 [215. 192. 187. 299. 299. 299. 299. 299. 299. 299.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [215. 191. 187. 186. 299. 299. 299. 299. 299. 299.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [243. 244. 239. 236. 236. 279. 299. 299. 299. 299.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [299. 299. 299. 299. 299. 299. 299. 299. 299. 299.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [299. 299. 299. 299. 299. 299. 299. 299. 299. 299.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]]
[[  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.  43.  37.  35. 299. 299. 299. 299. 299. 299.]
 [  1.  43.  38. 299. 299. 299. 299. 299. 299. 299.]
 [  1.  43.  38. 299. 299. 299. 299. 299. 299. 299.]
 [  1.  43.  38. 299. 299. 299. 299. 299. 299. 299.]
 [  1.  43.  38. 299. 299. 299. 299. 299. 299. 299.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.  45.  44.  44. 299. 299. 299. 299. 299. 299.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.  61.  63.  69.  75. 112. 299. 299. 299. 299.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1. 299. 299. 299. 299. 299. 299. 299. 299. 299.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1. 299. 299. 299. 299. 299. 299. 299. 299. 299.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]]
[[  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1. 141. 249. 299. 299. 299. 299. 299. 299. 299.]
 [ 29. 193. 292. 299. 299. 299. 299. 299. 299. 299.]
 [ 85. 233. 299. 299. 299. 299. 299. 299. 299. 299.]
 [130. 263. 299. 299. 299. 299. 299. 299. 299. 299.]
 [163. 291. 299. 299. 299. 299. 299. 299. 299. 299.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [230. 299. 299. 299. 299. 299. 299. 299. 299. 299.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [287. 299. 299. 299. 299. 299. 299. 299. 299. 299.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [299. 299. 299. 299. 299. 299. 299. 299. 299. 299.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [299. 299. 299. 299. 299. 299. 299. 299. 299. 299.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]]
[[  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  2. 115. 275. 299. 299. 299. 299. 299. 299. 299.]
 [ 25. 186. 299. 299. 299. 299. 299. 299. 299. 299.]
 [ 63. 256. 299. 299. 299. 299. 299. 299. 299. 299.]
 [108. 299. 299. 299. 299. 299. 299. 299. 299. 299.]
 [152. 299. 299. 299. 299. 299. 299. 299. 299. 299.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [277. 299. 299. 299. 299. 299. 299. 299. 299. 299.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [299. 299. 299. 299. 299. 299. 299. 299. 299. 299.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [299. 299. 299. 299. 299. 299. 299. 299. 299. 299.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [299. 299. 299. 299. 299. 299. 299. 299. 299. 299.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]]
[[  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.  34.  34.  33. 299. 299. 299. 299. 299. 299.]
 [ 19.  36.  34. 299. 299. 299. 299. 299. 299. 299.]
 [ 34.  36.  34. 299. 299. 299. 299. 299. 299. 299.]
 [ 39.  36.  34. 299. 299. 299. 299. 299. 299. 299.]
 [ 40.  37.  34. 299. 299. 299. 299. 299. 299. 299.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [ 42.  38.  44.  51. 299. 299. 299. 299. 299. 299.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [ 45.  56.  67.  78.  84. 118. 299. 299. 299. 299.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [ 92. 256. 299. 299. 299. 299. 299. 299. 299. 299.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [169. 299. 299. 299. 299. 299. 299. 299. 299. 299.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]]
[[  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  2.  23.  22.  20. 299. 299. 299. 299. 299. 299.]
 [ 17.  24.  22. 299. 299. 299. 299. 299. 299. 299.]
 [ 25.  24.  22. 299. 299. 299. 299. 299. 299. 299.]
 [ 28.  24.  22. 299. 299. 299. 299. 299. 299. 299.]
 [ 29.  24.  22. 299. 299. 299. 299. 299. 299. 299.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [ 30.  25.  26.  28. 299. 299. 299. 299. 299. 299.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [ 31.  35.  39.  45.  49.  76. 299. 299. 299. 299.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [ 62. 183. 299. 299. 299. 299. 299. 299. 299. 299.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [153. 299. 299. 299. 299. 299. 299. 299. 299. 299.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]]])
print(lifetime)
for init in range(8):
    #plt.cla()
    lifeini=lifetime[:,:,init]
    lifet=lifeini.transpose()
    #lifet=lifet[:,9]
    #lifet=lifet[4,:]
    print(lifet)
    print(init)
    plt.plot(lifet)
    #plt.show()

SyntaxError: invalid syntax (<ipython-input-39-fd9648db421b>, line 1)

In [32]:
for init in range(8):
    print(lifetime[:,:,i])

IndexError: index 17 is out of bounds for axis 2 with size 8